# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9.2'  # Adjust to your Swift version

    - name: Build
      run: swift build --build-tests

    - name: Test and generate code coverage
        run: | 
          swift test --enable-code-coverage --sanitize=thread
          mkdir -p ./coverage
          llvm-cov export -format=lcov ./debug/YourTargetNamePackageTests.xctest/Contents/MacOS/YourTargetNamePackageTests -instr-profile ./debug/YourTargetNamePackageTests.xctest/Contents/MacOS/YourTargetNamePackageTests.profdata > ./coverage/lcov.info

      - name: Upload code coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
      
